version: '3.5'
services:
  bitwarden-rs:
    build:
      context: https://github.com/dani-garcia/bitwarden_rs.git#${currenttag:-master}
    image: bitwardenrs/server:${currenttag:-latest}
    restart: always
    env_file: ./env
    ports:
      - "80:9080"
      - "3012:3012"
    volumes:
      - /var/lib/bitwarden_rs:/data/
      - /etc/localtime:/etc/localtime:ro
