version: '3.5'
services:
  vaultwarden:
    build:
      context: https://github.com/dani-garcia/vaultwarden.git#${currenttag:-master}
    image: vaultwarden/server:${currenttag:-latest}
    container_name: vaultwarden
    restart: always
    env_file: ./env
    ports:
      - "80:9080"
    volumes:
      - /var/lib/vaultwarden:/data/
      - /etc/localtime:/etc/localtime:ro
